---
title: "Metabolic Costs of Sexual Weapon"
author: "Naval Beekarun"
date: "2025-03-02"
output: html_document
---

### Load the data 
```{r}
data <- read.csv("data/MetabolicCosts.csv",sep=";")
```
```{r}
# Load the data
```
### Load the libraries
```{r}
library(tidyverse)

```
 

### Looking at the structure of the data 
```{r}
head(data)
```
### looking at the structure of the data
```{r}
str(data)
```
### checking if the file exists 
```{r}
file.exists("data/MetabolicCosts.csv")
```
### seeing the column names 
```{r}
colnames(MetabolicCosts)
```


### Changing the column names 
```{r}
head(MetabolicCosts)
```
```{r}
sum(is.na(MetabolicCosts))

```
```{r}
summary(MetabolicCosts)

```
```{r}
colnames(MetabolicCosts) <- c("ID", "Hind_Leg_Mass", "Body_Mass_g", "Pre_MR_Avg", "Post_MR_Avg", "Size")
```
```{r}
head(MetabolicCosts)
```


```{r}
## Create the plot with color based on 'Size' (large, medium, small)
ggplot(MetabolicCosts, aes(x = Hind_Leg_Mass, y = Pre_MR_Avg, color = Size)) +
  geom_point() +
  labs(title = "Hind Leg Mass vs. Metabolic Rate Before Leg Loss",
       x = "Hind Leg Mass (g)",
       y = "Metabolic Rate (Pre-Leg Loss)",
       color = "Size Category") +
  theme_minimal()
```

```{r}
## Create the plot with color based on 'Size' (large, medium, small)
ggplot(MetabolicCosts, aes(x = Hind_Leg_Mass, y = Post_MR_Avg, color = Size)) +
  geom_point() +
  labs(title = "Hind Leg Mass vs. Metabolic Rate After Leg Loss",
       x = "Hind Leg Mass (g)",
       y = "Metabolic Rate (Post-Leg Loss)",
       color = "Size Category") +
  theme_minimal()
```


```


```

```
```{r}

```
```{r}

```


```


```

```{r}

```


```
  
```




```


```


```

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

